from django.urls import path
from .views import IndexPageView, LoginPageView, Index1PageView, Index2PageView, AboutPageView, AdmissionPageView, AllCoursesPageView, AwardsPageView, SeminarPageView, EventsPageView, EventregisterPageView, BlogdetailsPageView, BlogPageView, ContactusPageView, CoursedetailsPageView, DashboardPageView, DbcoursesPageView, DbexamsPageView, DbprofilePageView, DbtimelinePageView, DepartmentsPageView, EventdetailsPageView, FacilitiesPageView, FacilitiesdetailPageView, ResearchPageView, GalleryphotoPageView,AdminAboutmenuPageView, AdminAddcoursesPageView, AdminAdmissionenquiryPageView, AdminAdmissionmenuPageView, AdminAllcoursesPageView, AdminAllenquiryPageView, AdminAllmenuPageView 
urlpatterns = [
path('', IndexPageView.as_view(), name='index'),
path('about/', AboutPageView.as_view(), name='about'),
path('admin-about-menu/', AdminAboutmenuPageView.as_view(), name='admin-about-menu'),
path('admin-add-courses/', AdminAddcoursesPageView.as_view(), name='admin-add-courses'),
path('admin-admission-enquiry/', AdminAdmissionenquiryPageView.as_view(), name='admin-admission-enquiry'),
path('admin-admission-menu/', AdminAdmissionmenuPageView.as_view(), name='admin-admission-menu'),
path('admin-all-courses/', AdminAllcoursesPageView.as_view(), name='admin-all-courses'),
path('admin-all-enquiry/', AdminAllenquiryPageView.as_view(), name='admin-all-enquiry'),
path('admin-all-menu/', AdminAllmenuPageView.as_view(), name='admin-all-menu'),
path('admission/', AdmissionPageView.as_view(), name='admission'),
path('all-courses/', AllCoursesPageView.as_view(), name='all-courses'),
path('awards/', AwardsPageView.as_view(), name='awards'),
path('blog/', BlogPageView.as_view(), name='blog'),
path('blog-details/', BlogdetailsPageView.as_view(), name='blog-details'),
path('contact-us/', ContactusPageView.as_view(), name='contact-us'),
path('course-details/', CoursedetailsPageView.as_view(), name='course-details'),
path('dashboard/', DashboardPageView.as_view(), name='dashboard'),
path('db-courses/', DbcoursesPageView.as_view(), name='db-courses'),
path('db-exams/', DbexamsPageView.as_view(), name='db-exams'),
path('db-profile/', DbprofilePageView.as_view(), name='db-profile'),
path('db-time-line/', DbtimelinePageView.as_view(), name='db-time-line'),
path('departments/', DepartmentsPageView.as_view(), name='departments'),
path('events/', EventsPageView.as_view(), name='events'),
path('event-details/', EventdetailsPageView.as_view(), name='event-details'),
path('event-register/', EventregisterPageView.as_view(), name='event-register'),
path('facilities/', FacilitiesPageView.as_view(), name='facilities'),
path('facilities-detail/', FacilitiesdetailPageView.as_view(), name='facilities-detail'),
path('gallery-photo/', GalleryphotoPageView.as_view(), name='gallery-photo'),
path('index-1', Index1PageView.as_view(), name='index-1'),
path('index-2', Index2PageView.as_view(), name='index-2'),
path('research/', ResearchPageView.as_view(), name='research'),
path('seminar/', SeminarPageView.as_view(), name='seminar'),
]